#logging.level.org.springframework.web: DEBUG

spring:
  application:
    name: atlas

  data:
      mongodb:
        database: atlas
        uri: mongodb://localhost:27017
  datasource:
      url: jdbc:mysql://localhost:3306/atlas
      username: username
      password: password

spring.social.twitter.appId: XXXXX
spring.social.twitter.appSecret: XXXXX
