#logging.level.org.springframework.web: DEBUG

spring:
  application:
    name: atlas

  data:
      mongodb:
        database: atlas
        uri: mongodb://localhost:27017
  datasource:
      url: jdbc:mysql://localhost:3306/atlas
      username: XXXX
      password: YYYY

  social:
      twitter:
        appId: WWWWWW
        appSecret: VVVVVV

# For development only. It generates the tables, deleting existing data.
#  jpa:
#    database: MYSQL
#    show-sql: true
#    hibernate.ddl-auto: create
